name: Upload Website
on:
  workflow_run:
    workflows: ["Build Website"]
    types:
      - completed
jobs:
  upload:
    name: Upload Website
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # 下载构建产物
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: website-build
          path: stored-build
      # 检出目标仓库
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: Grain-Kitty/Web-For-Show
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: target-repo
      # 复制构建产物到目标仓库
      - name: Copy Build Output to Target Repository
        run: |
          Copy-Item -Path stored-build\* -Destination target-repo -Recurse
      # 提交并推送更改到目标仓库
      - name: Commit and Push to Target Repository
        run: |
          cd target-repo
          git config user.name "Grain-Kitty"
          git config user.email "yuwenpei983@gmail.com"
          git add.
          git commit -m "upload from Web-For-building"
          git push origin main
