name: Build Website
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Website
    runs-on: windows-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 复制环境变量文件
      - name: Copy.env.example
        run: |
          if (-not (Test-Path.env)) {
            Copy-Item.env.example.env
          } else {
            Write-Host ".env file already exists. Skipping the copy step."
          }
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install --force
      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # 存储构建产物
      - name: Store Build Output
        run: |
          New-Item -ItemType Directory -Force -Path stored-build
          Copy-Item -Path dist\* -Destination stored-build -Recurse
      # 上传构建产物作为 Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website-build
          path: stored-build
